### ISSUE TITLE
How to exit vim?

### ISSUE THREAD

**Issue by jobpaardekooper** [oakes/vim_cubed#1]

**Comment by oakes** [comment]
vim³ isn't for quitters

**Comment by theJian** [comment]
Press the power button on your computer. It works for me.

**Comment by victorb** [comment]
Another way if you're on linux: Hold Alt + SysRq and press/let go in sequence: `r e i s u b`

**Comment by NieDzejkob** [comment]
No need for such drastic means, quitting Vim is much simpler. Make sure you're in normal mode, then type `:execute "!kill -9 " . getpid()`

**Comment by ron-wolf** [comment]
Help I’m trapped in Vim and I can only communicate through this GitHub issues browser I wrote in VimL

**Comment by Pikamander2** [comment]
I'm having the same problem. Does anyone know how to exit vim?
