### ISSUE TITLE
error: GLSL 4.10 is not supported.

### ISSUE THREAD

**Issue by sheerluck** [oakes/vim_cubed#25]
```
$ glxinfo | grep "Max core profile"
    Max core profile version: 3.3
```

**Comment by oakes** [comment]
try changing [these lines](https://github.com/oakes/vim_cubed/blob/7264e53b716b423855d53ac1f0eb3f7f6f2b502c/src/vim3.nim#L22-L23) to use 3 and 3. maybe that will work, i haven't tried.

**Comment by oakes** [comment]
oh the shaders also declare a `#version`, that may need to change too.

**Comment by sheerluck** [comment]
I am afraid content of `fragment.glsl` and `vertex.glsl` is incompatible with 3.3 even if I change  `#version 410` to `#version 330`

**Comment by oakes** [comment]
did you change the shaders [here](https://github.com/paranim/paravim/tree/master/src/paravim/shaders) and [here](https://github.com/paranim/paranim/blob/master/src/paranim/gl/entities.nim)? they are separate libraries so it'll be a bit inconvenient to test but if you run `nimble develop` in those repos it will make this project use them. i haven't checked if the glsl actually is compatible with 3.3 though.

**Comment by sheerluck** [comment]
thank you, I suddenly found device with `Max core profile version: 4.5` so problem solved :)

**Comment by oakes** [comment]
in case anyone else had this issue, i reduced the required opengl version to 3.3
