### ISSUE TITLE
Unable to install vim3 using nimble

### ISSUE THREAD

**Issue by milad2golnia** [oakes/vim_cubed#28]
I am completely new to NIM language but I want to install vim3.
when i run `nimble run vim3`, the output is:
```

Verifying dependencies for vim3@0.1.0
 Installing paranim@>= 0.3.0
Downloading https://github.com/paranim/paranim using git
  Verifying dependencies for paranim@0.3.0
 Installing nimgl@>= 1.0.0
Downloading https://github.com/nimgl/nimgl using git
```
and then nothing happens.
what is the problem?
NOTE: I tried `git clone https://github.com/nimgl/nimgl` and the repository cloned normally.

**Comment by oakes** [comment]
are you on linux? see the bottom of the readme if so

**Comment by milad2golnia** [comment]
> are you on linux? see the bottom of the readme if so

Yes, I am on Manjaro(which is arch based). I tried `sudo ln -s /usr/lib/libssl.so /usr/lib/libssl-dev.so` but still same problem.
NOTE: below packages aren't available in Manjaro: `libtinfo5, libgl1-mesa-dev, xorg-dev`.

**Comment by oakes** [comment]
hmm what made you try that with libssl? that's not in the readme

**Comment by milad2golnia** [comment]
> hmm what made you try that with libssl? that's not in the readme

Sorry, It was typo. I tried `sudo ln -s /usr/lib/libtinfo.so.6 /usr/lib/libtinfo.so.5` right now and the output is:
`ln: failed to create symbolic link '/usr/lib/libtinfo.so.5': File exists
`
what should I do?

**Comment by oakes** [comment]
i don't think your issue is libtinfo, that would be a runtime error. you may need to find the arch equivalents to libgl1-mesa-dev (opengl) and xorg-dev (x11). can you try `nimble run vim3 --verbose` ? maybe that will give a better error

**Comment by milad2golnia** [comment]
> i don't think your issue is libtinfo, that would be a runtime error. you may need to find the arch equivalents to libgl1-mesa-dev (opengl) and xorg-dev (x11). can you try `nimble run vim3 --verbose` ? maybe that will give a better error

the result of `nimble run vim3 --verbose`:
```
Verifying dependencies for vim3@0.1.0
    Reading official package list
   Checking for paranim@>= 0.3.0
 Installing paranim@>= 0.3.0
    Reading official package list
Downloading https://github.com/paranim/paranim using git
    Cloning latest tagged version: 0.3.0
       Info /tmp/nimble_56998/githubcom_paranimparanim_0.3.0/paranim_56998.nims(1, 8) Warning: imported and not used: 'system' [UnusedImport]
        ... /tmp/nimble_56998/githubcom_paranimparanim_0.3.0/paranim_56998.nims(5, 22) Warning: imported and not used: 'strutils' [UnusedImport]
  Verifying dependencies for paranim@0.3.0
    Reading official package list
   Checking for nimgl@>= 1.0.0
 Installing nimgl@>= 1.0.0
    Reading official package list
Downloading https://github.com/nimgl/nimgl using git
    Cloning latest tagged version: 1.1.1
```
I found some equivalent and installed them but to no avail:(
I try to found some other again.

**Comment by milad2golnia** [comment]
Fortunately when i tried the `nimble run vim3 --verbose` again and after a while, I got it worked.
I didn't installed any library in this time and I didn't know what doesn't happened really.
After all I am so happy that have this program on my system and so I close this issue. 
just as an advise it will be great if user be able to set the speed of cube.
thank you very much. your responsibility was great.
