### ISSUE TITLE
The project title is misleading

### ISSUE THREAD

**Issue by iansuvak** [oakes/vim_cubed#9]
Vim cubed would imply 6-d since basic vim is already 2-d. Please either make it 6-d or rename  to vim^(3/2)

**Comment by Sergix** [comment]
No if vim is 2-d and this is vim cubed

2^3 = 8

Please make it 8-d

**Comment by arobase-che** [comment]
I don't get the point of vim 8-d.

It vim + 1 dim. So Vim 3D is fine. Since the last dimension use a cube Vim³ seems fine too.
